service: aws-python-prophet-rest-api

provider:
  name: aws
  region: eu-west-2
  runtime: python3.8
  apiGateway:
    shouldStartNameWithService: true
    

  # apiGatewayCaching:
  #   enabled: true
  #   ttlInSeconds: 300 # defaults to the maximum allowed: 3600
custom:
  pythonRequirements:
    noDeploy:
    - matplotlib
    dockerizePip: non-linux
    slim: true
    zip: true
    layer : true
    slimPatterns:
      - '**/tests/*'
      - '**/__pycache__*'
      - "**/stan/src/*"
      - "**/stan/lib/stan_math/lib/*"


package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: handler.predict
    events:
      - http:
          path: predict
          method: post
          cors: true


plugins:
  - serverless-python-requirements
  - serverless-offline-python
  # - serverless-api-gateway-caching
