name: deploy-aws-lambda

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
         python-version: '3.8'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install pandas
          pip install numpy
          pip install fbprophet
      - name: deploy
        run: npm run-script deploy
      - name : Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./
      
# pip install wheel==0.36.2
# pip install appdirs==1.4.4
# pip install autopep8==1.5.4
# pip install certifi==2020.6.20
# pip install cmdstanpy==0.9.5
# pip install convertdate==2.2.2
# pip install cycler==0.10.0
# pip install Cython==0.29.21
# pip install distlib==0.3.1
# pip install ephem==3.7.7.1
# pip install fbprophet==0.7.1
# pip install filelock==3.0.12
# pip install holidays==0.10.3
# pip install joblib==0.17.0
# pip install kiwisolver==1.2.0
# pip install korean-lunar-calendar==0.2.1
# pip install LunarCalendar==0.0.9
# pip install matplotlib==3.3.2
# pip install numpy==1.19.2
# pip install pandas==1.1.3
# pip install Pillow==8.0.0
# pip install pycodestyle==2.6.0
# pip install PyMeeus==0.3.7
# pip install pyparsing==2.4.7
# pip install pystan==2.19.1.1
# pip install python-dateutil==2.8.1
# pip install python-osrsapi==0.0.3
# pip install pytz==2020.1
# pip install scikit-learn==0.23.2
# pip install scipy==1.5.3
# pip install setuptools-git==1.2
# pip install six==1.15.0
# pip install sklearn==0.0
# pip install threadpoolctl==2.1.0
# pip install toml==0.10.1
# pip install tqdm==4.50.2
# pip install virtualenv==20.2.2
